spring.application.name=ruk-lk-api
spring.profiles.active=onec
app.onec.base-url=http://10.10.31.13/universitet_masterkova1
logging.level.org.springframework.security=DEBUG
app.onec.publication-user=Еременко Дмитрий Султанбекович
app.onec.publication-password=12345
