spring.application.name=ruk-lk-api
spring.profiles.active=onec
app.onec.base-url=http://10.10.31.13/universitet_masterkova1
spring.config.encoding=UTF-8
spring.config.import=optional:file:./application-local.properties
server.servlet.session.cookie.same-site=lax
app.onec.publication-user=
app.onec.publication-password=
# Фиксированный код для dev (переопределить в application-local.properties)
app.auth.fixed-code=
