/**
 * @file Маршруты приложения.
 * Ключи — для кода, значения — path в react-router.
 */

/** Карта разделов личного кабинета */
export const paths = {
  home: '/',
  login: '/login',
  loginStudent: '/login/student',
  loginDelivery: '/login/delivery',
  loginParent: '/login/parent',
  loginParentSelect: '/login/parent/select',
  loginParentVerify: '/login/parent/verify',
  loginContract: '/login/contract',
  loginTarget: '/login/target',
  loginTeacher: '/login/teacher',
  sso: '/login/sso',
  verify: '/verify-code',
  resources: '/resources',
  support: '/support',
  profile: '/profile',
  news: '/messages',
  schedule: '/schedule',
  education: '/education',
  grades: '/grades',
  recordBook: '/record-book',
  attendance: '/attendance',
  eJournal: '/e-journal',
  debts: '/debts',
  studyPlan: '/study-plan',
  roadmap: '/roadmap',
  teachers: '/teachers',
  orders: '/orders',
  services: '/services',
  requests: '/requests',
  payments: '/payments',
  dormitory: '/dormitory',
  bypassList: '/bypass-list',
  psychologist: '/psychologist',
  portfolio: '/portfolio',
  library: '/library',
  settings: '/settings',
  esports: '/esports',
  passPhoto: '/services/pass-photo',
  adminPassPhotos: '/admin/pass-photos',
  adminPassPhotosLogin: '/admin/pass-photos/login',
  adminPassPhotosSpo: '/admin/pass-photos/spo',
  adminPassPhotosHe: '/admin/pass-photos/he',
  /** @deprecated используйте adminPassPhotosLogin */
  adminPassPhotosSpoLogin: '/admin/pass-photos/spo/login',
  /** @deprecated используйте adminPassPhotosLogin */
  adminPassPhotosHeLogin: '/admin/pass-photos/he/login',
  parentHome: '/parent',
  parentSurvey: '/parent/survey',
  parentProfile: '/parent/profile',
  parentNews: '/parent/news',
  parentSchedule: '/parent/schedule',
  parentRecordBook: '/parent/record-book',
  parentAttendance: '/parent/attendance',
  parentPayments: '/parent/payments',
  parentOrders: '/parent/orders',
} as const
